# Generated by Django 4.2 on 2026-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MyNotes')),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
